server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    url: jdbc:mariadb://3.39.233.7:3306/song?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: song
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
#    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
# key 규칙 : cos는 붙여서, key는 앞에 스페이스바 두번, : 하고 스페이스바 한번
cos:
  key: song1234
      
      